### ISSUE TITLE
user comment: would be useful with lat / lon interpolated data to localize measurements

### ISSUE THREAD

**Issue by jerabaul29** [OpenDrift/trajan#103]
I got a user feedback: it would be easier for users if measurements (e.g. wave spectra / statistics) would have an associated lat / lon variable. This could simply be either a "closest GPS position" or a "linearly interpolated GPS position" depending on how the "surrounding" GPS positions look like. For now the user needs to do this.

I could try to implement something for the wave data in a bit general way (so it could also be applied to other measurements).

The result would be for example adding variables:

lat_waves_imu(trajectory, obs_waves_imu)
lon_waves_imu(trajectory, obs_waves_imu)

What do you think @gauteh ?

cc @oceandatalab :) .

**Comment by gauteh** [comment]
Yes, this is a common problem. What happens if you have thermistor readings at yet another timestamp? :) In trajan I think you should be able to do use `gridtimes` to get the positions at the imu times.

You risk loosing information about the lon lat as part of the interpolation, it should at least be very clear that these are processed positions. I also don't think they will work trajan (without removing the original positions).

**Comment by gauteh** [comment]
> > In trajan I think you should be able to do use gridtimes to get the positions at the imu times.
> 
> That shounds good - do you have an example snippet of recommended use? :) 

It is currently easy to grid positions to a 1d vector of times, but I don't think gridding each trajectory along different times is possible. This should be communicated to gridtimes with a `trajectory` dimension matching the dimension with different trajectories, probably not too difficult to implement. But it would result in adding a `obs` dimension if it is not already present, so it is possible to implement this into `gridtimes` (and make it even more powerful), but it could also be in a `gridobs` method. I'm leaning towards having this in `gridtimes`, because it will make the API very similar regardles of whether you have a structured or unstructured dataset.

**Comment by gauteh** [comment]
> A few technical thoughts:
> 
> * this performs a "simple" interpolation, which is perfectly fine, but I am wondering if I want to do a bit more sophisticated in my case e.g. in case of GNSS dropout, do not "wildly" interpolate if there is an obs with no GNSS "around" it, and if not "surrounded on both ends", use the closest instead of the linearly interpolated value; this could be either integrated directly in gridtime (adding an option about what kind of "interpolation" to use?), or a separate functionality

Absolutely. Preferably chain "remove outliers", etc and not make them options to interpolation.

> * this is a trajan function, and it could be convenient to re-use / extend / develop a functionality that provides the interpolated lat lon as a trajan functionality based on it, but as discussed over, for downstream users of the nc files who do not use trajan, it could also be good to "just" add variables with the coordinates directly in the nc file; this could be done by calling `gridtime` when building the OMB or similar trajan ds

Yes, even if you do pre-compute it would be more flexible to do this through trajan so that the functionality is available in general.

> * I need to look at how to implement the dimensions matching discussed in [user comment: would be useful with lat / lon interpolated data to localize measurements #103 (comment)](https://github.com/OpenDrift/trajan/issues/103#issuecomment-2345455985) .

Here's an example of how you can use dimensions in xarray to communicate how methods should be applied:
https://opendrift.github.io/trajan/gallery/example_model_along_trajectory.html#sphx-glr-gallery-example-model-along-trajectory-py

This is a very powerful concept compared to un-annotated arrays in numpy where you always need to keep track of dimension order and broadcasting manually.

**Comment by gauteh** [comment]
You can provide an irregular array of times, so gridtime could perhaps be called interptime.

**Comment by gauteh** [comment]
Yes, it might be cleaner to do this on a variable. The traj accessor is currently on the dataset, but it could also be registered on a variable. The essential part for xarray is to create a `times` dataarray with dimensions time and trajectory, then interp will either manage to choose the correct times for each trajectory -- or we would have to iterate and match trajectories to each other in gridtimes. 

But I agree that doing this on the variable is better when things get a bit more messy. It's convenient to interpolate the whole dataset when possible, but many variables are not obvious how they should be interpolated (drifter names.. ?). Even if it is done on a variable you will have the same problem with the trajectory dimension.

**Comment by knutfrode** [comment]
Not sure if you have discussed this already, but it is quite inconvenient with several time axes in a dataset, with different corresponding variables. I guess this was not foreseen for TrajAn at the beginning, but has become necessary due to the specifics of buoys measuring wave spectra.

Thinking loudly: perhaps it was best if An Xarray/TrajAn-dataset simply contains a single time axis, so that when opening a dataset with several time-axes, one either gets a "group of datasets" (with a single time dimension each), or alternatively that one have to chose one of the time-axes upon reading/importing? This might simplify some things considerably (though also introduce new challenges).

**Comment by gauteh** [comment]
Currently trajan can confidently detect the interesting time dimension because it looks for coordinate or time dimension related to position data. In all cases I can think of right now this becomes clear once you select which variable you are looking at. Which means that often by adding the accessor on the dataarray things will be resolved, and for the dataset wide operations trajan has to pick the variables that are related through the time variable on the position data. In the beginning trajan detects these now, and ignores the rest of the dataset.

**Comment by knutfrode** [comment]
> That shounds good - do you have an example snippet of recommended use? :) My 2 cents: it could be very nice to introduce this functionality as a trajan function / use existing functionality. At the same time, not all users of the nc files use trajan / have the possibility to run much code on their end. I think the point of @oceandatalab was that it would be good if all of this is included "by default" in the nc files, so that any viewer or tool can just enter the name of the lat / lon corresponding to each data field, and get these plotted out of the box, without the need to run some additional code (maybe some viewers by default do not even use / are not written in python, then it is a bit painful to point these users to using trajan?). What do you think? :) Of course this means heavier files, but these files are so lightweight anyways that it should not be an issue? :)

Not sure if I completely understood, but if following the CF convention precisely, a proper plotter/postprocessor should be able to link any variables with the correct geolocation, as well as temporal axis. Thus without any need for human/manual guidance. I guess this is with the `grid_mapping` and/or `coordinates` attributes. (I have by no means a complete overview/understanding of all aspects of the CF-convention, but we should strive to be as compliant as possible).
https://cfconventions.org/Data/cf-conventions/cf-conventions-1.11/cf-conventions.html#coordinate-system
There are probably many improvements to be made for TrajAn output. We could include a validator in the test-suite, e.g. https://github.com/cedadev/cf-checker

**Comment by knutfrode** [comment]
> I think this is mainly a problem for any system that need "non-observation" data, i.e.: the data must have time as a regular coordinate. In practice there are probably going to be a bunch of relevant tools that will never support this. I'm more in favor of making it easy to produce such data with trajan than having it by default. Whoever is doing this production needs to set up a small script anyway, and in that case a few more lines of trajan code is better than very specifically produced data in the first place.

Ok, yes this makes sense.
Indeed, not many (if any) datasets and softwares are 100% CF-compliant, able to handle all aspects of any dataset automatically. But this could still be a goal.
